//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobile_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileInfo
    {
        public int ModelNo { get; set; }
        public string Brand { get; set; }
        public string Weight { get; set; }
        public string Resolution { get; set; }
        public string DisplayType { get; set; }
        public string OS { get; set; }
        public string Chipset { get; set; }
        public string RAM { get; set; }
        public string Storage { get; set; }
        public string MainCamera { get; set; }
    }
}
